---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: file-uploader
  name: file-uploader
  namespace: file-uploader
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: file-uploader
  name: file-uploader
  namespace: file-uploader
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: file-uploader:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/christianh814/openshift-php-upload-demo
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.1
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}
  - github:
      secret: XY1KKw02HTYBtiYoQfaC
    type: GitHub
  - generic:
      secret: bsJ6R5jWFfTjnKJMIIjV
    type: Generic
